name: CWTools CI

on: [pull_request, push] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.1.0
      with:
        game: stellaris
        modPath: "mod"
        locLanguages: "english german"
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
